<style type="text/css">
</style>

<h1>Doctors</h1>
<table>
<!-- Headers -->
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Surname</th>
		<th><!-- Appointments --></th>
		<th><!-- Email --></th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>

<?php foreach($this->doctors as $doctor): ?>
<!-- Data -->
	<tr>
		<td> <?= $doctor->id ?> </td>
		<td> <?= $doctor->name ?> </td>
		<td> <?= $doctor->surname ?> </td>
		<td> 
			<a href="
				<?= $this->url('admin', array(
						'action' => 'appointments', 
						'id' => $doctor->id
					));
				?>">appointments
			</a>
		</td>
		<td> <a href="mailto:<?= $doctor->email ?> ">email</a> </td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'editdoctor', 
						'id' => $doctor->id
					)); ?>">edit
			</a> 
		</td>
		<td> 
			<a href="
				<?= $this->url('admin', array(
						'action' => 'deletedoctor', 
						'id' => $doctor->id
					)); ?>">delete
			</a> 
		</td>
	</tr>

<?php endforeach; ?>

</table>