
<h1>Patients</h1>

<table>
<!-- Headers -->
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Surname</th>
		<th><!-- Appointments --></th>
		<th><!-- Email --></th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>

<?php foreach($this->patients as $patient): ?>
<!-- Data -->
	<tr>
		<td> <?= $patient->getId() ?> </td>
		<td> <?= $patient->getName() ?> </td>
		<td> <?= $patient->getSurname() ?> </td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'appointments',
						'id' => $patient->getId()
					));
				?>">appointments
			</a>
		</td>
		<td> <a href="mailto:<?= $patient->getEmail() ?> ">email</a> </td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'editpatient',
						'id' => $patient->getId()
					)); ?>">edit
			</a>
		</td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'deletepatient',
						'id' => $patient->getId()
					)); ?>">delete
			</a>
		</td>
	</tr>

<?php endforeach; ?>

</table>