
<h1>Practitioners</h1>

<table>
<!-- Headers -->
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Surname</th>
		<th>Supervisor</th>
		<th><!-- Appointments --></th>
		<th><!-- Email --></th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>

<?php foreach($this->practitioners as $practitioner): ?>
<!-- Data -->
	<tr>
		<td> <?= $practitioner->getId() ?> </td>
		<td> <?= $practitioner->getName() ?> </td>
		<td> <?= $practitioner->getSurname() ?> </td>
		<td> <?= "Dr. {$practitioner->getSuperVisor()->getName()}
				 {$practitioner->getSuperVisor()->getSurname()}"  ?></td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'appointments',
						'id' => $practitioner->getId()
					));
				?>">appointments
			</a>
		</td>
		<td> <a href="mailto:<?= $practitioner->getEmail() ?> ">email</a> </td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'editpractitioner',
						'id' => $practitioner->getId()
					)); ?>">edit
			</a>
		</td>
		<td>
			<a href="
				<?= $this->url('admin', array(
						'action' => 'deletepractitioner',
						'id' => $practitioner->getId()
					)); ?>">delete
			</a>
		</td>
	</tr>

<?php endforeach; ?>

</table>