
<?php 

// Prepare Form

$form = $this->form;

$form->setAttribute('action', $this->url('admin', array('action' => 'registerdoctor')));
$form->prepare();
echo $this->form()->openTag($form);

?>
<h1>Add doctor</h1>
	<?php echo $this->formLabel($form->get('name'));?>
<br>	<?php echo $this->formInput($form->get('name'));?>
<br>	<?php echo $this->formLabel($form->get('surname'));?>
<br>	<?php echo $this->formInput($form->get('surname'));?>
<br>	<?php echo $this->formLabel($form->get('email'));?>
<br>	<?php echo $this->formInput($form->get('email'));?>
<br>	<?php echo $this->formLabel($form->get('password'));?>
<br>	<?php echo $this->formInput($form->get('password'));?>
<br><br>	<?php echo $this->formInput($form->get('submit'));?>

<?php $this->form()->closeTag($form); ?>